SCMOD-7700: Stop container if script execution fails
caf-archive/opensuse-base-image pull request #14
Opened 2020-06-03 03:48 UTC by kusumaghoshdastidar

Jira: https://portal.digitalsafe.net/browse/SCMOD-7700

2020-06-03 03:50 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/CAFapi/job/CAFapi~opensuse-base-image~SCMOD-7700~CI

2020-06-04 00:45 UTC, dermot-hardy commented on src/main/docker/startup/startup.sh
> +            log "Successfully ran ${script##*/}"
There is no need for this extra unnecessary logging.

2020-06-04 00:47 UTC, dermot-hardy commented on src/main/docker/startup/startup.sh
> +            log "Successfully ran ${script##*/}"
Get rid of the success branch.

2020-06-04 09:40 UTC, michael-bryson commented
@dermot-hardy I know this is a bug fix but it still could be viewed as a breaking change, what do you think? It is changing the behaviour of how the image is starting up.

2020-06-04 14:34 UTC, dermot-hardy requested changes
That's a fair point.  It's possible that this _bug_ is being replied upon.  I agree we should treat this as a breaking change.  It will also be a breaking change in all downstream base images which move to it.

2020-06-04 17:59 UTC, dermot-hardy approved these changes

2020-06-04 17:59 UTC, merged